// Mocks generated by Mockito 5.4.4 from annotations
// in random_quote_generator/test/application/random_quote/bloc/random_quote_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:random_quote_generator/data/models/random_quote_model.dart'
    as _i7;
import 'package:random_quote_generator/domain/failures/failures.dart' as _i6;
import 'package:random_quote_generator/domain/repositories/random_quote_repo.dart'
    as _i2;
import 'package:random_quote_generator/domain/usecases/random_quote_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRandomQuoteRepo_0 extends _i1.SmartFake
    implements _i2.RandomQuoteRepo {
  _FakeRandomQuoteRepo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RandomQuoteUseCases].
///
/// See the documentation for Mockito's code generation for more information.
class MockRandomQuoteUseCases extends _i1.Mock
    implements _i4.RandomQuoteUseCases {
  @override
  _i2.RandomQuoteRepo get randomQuoteRepo => (super.noSuchMethod(
        Invocation.getter(#randomQuoteRepo),
        returnValue: _FakeRandomQuoteRepo_0(
          this,
          Invocation.getter(#randomQuoteRepo),
        ),
        returnValueForMissingStub: _FakeRandomQuoteRepo_0(
          this,
          Invocation.getter(#randomQuoteRepo),
        ),
      ) as _i2.RandomQuoteRepo);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.RandomQuoteDTO>> getRandomQuote() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomQuote,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.RandomQuoteDTO>>.value(
                _FakeEither_1<_i6.Failure, _i7.RandomQuoteDTO>(
          this,
          Invocation.method(
            #getRandomQuote,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, _i7.RandomQuoteDTO>>.value(
                _FakeEither_1<_i6.Failure, _i7.RandomQuoteDTO>(
          this,
          Invocation.method(
            #getRandomQuote,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.RandomQuoteDTO>>);
}
